# Generated by Django 2.0.1 on 2019-01-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.FileField(upload_to='card_detector/Images')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
