# Generated by Django 2.0.1 on 2019-10-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0003_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='about',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
