# Generated by Django 2.0.1 on 2019-10-15 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20191014_2230'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('stage', '0004_user_profile_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
