# Generated by Django 2.1.2 on 2018-11-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20181023_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_info',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
