# Generated by Django 2.1.3 on 2018-11-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_login_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('photo_ID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pic', models.ImageField(upload_to='pictures')),
            ],
            options={
                'db_table': 'Photos',
            },
        ),
    ]
