# Generated by Django 2.1.3 on 2018-11-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='pic',
            field=models.ImageField(upload_to='image-save-test'),
        ),
        migrations.AlterModelTable(
            name='photos',
            table='Photo_db',
        ),
    ]
