# Generated by Django 2.1.3 on 2018-11-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20181120_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='pic',
            field=models.ImageField(upload_to='Blog/static/Uploaded_Images'),
        ),
    ]
