# Generated by Django 2.2.6 on 2019-10-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='stars',
            new_name='star',
        ),
    ]
