# Generated by Django 2.2.6 on 2019-10-27 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_pizza_topping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
