# Generated by Django 2.2.6 on 2019-10-27 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0004_auto_20191027_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='star',
        ),
        migrations.AddField(
            model_name='post',
            name='star',
            field=models.ManyToManyField(related_name='blog_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
