# Generated by Django 2.0.1 on 2019-10-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20191014_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
