# Generated by Django 2.2 on 2019-11-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20191027_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='star',
        ),
    ]
