# Generated by Django 2.0.1 on 2019-10-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_remove_comment_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='stars',
        ),
    ]
