# Generated by Django 2.2.6 on 2019-10-20 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hal_il', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='list',
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
