# Generated by Django 2.0.1 on 2019-01-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
